const menuToggle=document.getElementById('menuToggle');const mainNav=document.getElementById('mainNav');
const siteHeader=document.querySelector('.site-header');const updateHeaderScroll=()=>{if(siteHeader)siteHeader.classList.toggle('is-scrolled',window.scrollY>50)};window.addEventListener('scroll',updateHeaderScroll,{passive:true});updateHeaderScroll();
if(menuToggle&&mainNav){const closeMenu=()=>{mainNav.classList.remove('open');document.body.classList.remove('menu-open');menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label','Open navigation menu')};menuToggle.addEventListener('click',()=>{const open=mainNav.classList.toggle('open');document.body.classList.toggle('menu-open',open);menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?'Close navigation menu':'Open navigation menu')});mainNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});document.addEventListener('click',e=>{if(!mainNav.contains(e.target)&&!menuToggle.contains(e.target))closeMenu()})}
const translations={};let currentLang='en';const langToggle=document.getElementById('langToggle');
function setLanguage(lang){currentLang=lang;document.documentElement.lang=lang==='bn'?'bn':'en';document.querySelectorAll('[data-en][data-bn]').forEach(el=>{el.innerHTML=el.dataset[lang]});document.querySelectorAll('[data-placeholder-en][data-placeholder-bn]').forEach(el=>{el.placeholder=el.dataset['placeholder'+(lang==='bn'?'Bn':'En')]});if(langToggle)langToggle.textContent=lang==='en'?'বাংলা':'English';renderCountries();}
if(langToggle)langToggle.addEventListener('click',()=>setLanguage(currentLang==='en'?'bn':'en'));
const countries=[
{n:'Bangladesh',bn:'বাংলাদেশ',r:'South Asia',cap:'Dhaka',capbn:'ঢাকা',img:'photo-1589308078059-be1415eab4c3',heritage:'The Sundarbans, river landscapes, terracotta temples and the living traditions of Bengali language and crafts.',heritagebn:'সুন্দরবন, নদীমাতৃক ভূদৃশ্য, পোড়ামাটির মন্দির এবং বাংলা ভাষা ও কারুশিল্পের জীবন্ত ঐতিহ্য।',history:'The region has a long history shaped by ancient Bengal, Buddhist and Hindu kingdoms, the Bengal Sultanate and the 1971 Liberation War.',historybn:'প্রাচীন বঙ্গ, বৌদ্ধ ও হিন্দু রাজ্য, বাংলা সালতানাত এবং ১৯৭১ সালের মুক্তিযুদ্ধ এই অঞ্চলের ইতিহাস গড়েছে।'},
{n:'India',bn:'ভারত',r:'South Asia',cap:'New Delhi',capbn:'নয়াদিল্লি',img:'photo-1524492412937-b28074a5d7da',heritage:'The Taj Mahal, temple architecture, classical dance, regional cuisines and many living languages.',heritagebn:'তাজমহল, মন্দির স্থাপত্য, শাস্ত্রীয় নৃত্য, আঞ্চলিক খাবার ও বহু জীবন্ত ভাষা।',history:'The subcontinent includes the Indus Valley civilisation, ancient empires, the Mughal era and the independence movement.',historybn:'এই উপমহাদেশে সিন্ধু সভ্যতা, প্রাচীন সাম্রাজ্য, মুঘল যুগ এবং স্বাধীনতা আন্দোলনের ইতিহাস রয়েছে।'},
{n:'Nepal',bn:'নেপাল',r:'South Asia',cap:'Kathmandu',capbn:'কাঠমান্ডু',img:'photo-1544735716-392fe2489ffa',heritage:'Himalayan landscapes, Newar architecture, Buddhist stupas and Hindu pilgrimage sites.',heritagebn:'হিমালয়ের দৃশ্য, নেওয়ার স্থাপত্য, বৌদ্ধ স্তূপ ও হিন্দু তীর্থস্থান।',history:'Kathmandu Valley grew as a historic centre of Himalayan trade, art and the Malla kingdoms; modern Nepal unified in the 18th century.',historybn:'কাঠমান্ডু উপত্যকা হিমালয় বাণিজ্য, শিল্প ও মল্ল রাজ্যগুলোর ঐতিহাসিক কেন্দ্র ছিল; আধুনিক নেপাল ১৮শ শতকে একীভূত হয়।'},
{n:'Bhutan',bn:'ভুটান',r:'South Asia',cap:'Thimphu',capbn:'থিম্পু',img:'photo-1626621341517-bbf3d9990a23',heritage:'Dzongs, cliffside monasteries, masked festivals and Himalayan Buddhist traditions.',heritagebn:'জং দুর্গ, পাহাড়ের গায়ে মঠ, মুখোশ নৃত্য উৎসব ও হিমালয়ান বৌদ্ধ ঐতিহ্য।',history:'Bhutan’s history is closely linked to Himalayan Buddhism and the consolidation of a unified kingdom in the 17th century.',historybn:'ভুটানের ইতিহাস হিমালয়ান বৌদ্ধধর্ম ও ১৭শ শতকে ঐক্যবদ্ধ রাজ্য প্রতিষ্ঠার সঙ্গে গভীরভাবে যুক্ত।'},
{n:'Pakistan',bn:'পাকিস্তান',r:'South Asia',cap:'Islamabad',capbn:'ইসলামাবাদ',img:'assets/country-pakistan.jpg',heritage:'Mughal monuments, Lahore’s walled city, mountain valleys and the ancient sites of Mohenjo-daro.',heritagebn:'মুঘল স্থাপনা, লাহোরের প্রাচীন নগর, পাহাড়ি উপত্যকা ও মহেঞ্জোদারোর প্রাচীন নিদর্শন।',history:'The land contains major Indus Valley sites and later Gandhara, Sultanate and Mughal cultural layers.',historybn:'এ অঞ্চলে সিন্ধু সভ্যতার গুরুত্বপূর্ণ স্থান এবং পরে গান্ধার, সালতানাত ও মুঘল সংস্কৃতির স্তর রয়েছে।'},
{n:'Sri Lanka',bn:'শ্রীলঙ্কা',r:'South Asia',cap:'Sri Jayawardenepura Kotte',capbn:'শ্রী জয়বর্ধনেপুরা কোট্টে',img:'assets/country-sri-lanka.jpg',heritage:'Ancient cities, Buddhist temples, tea-country scenery, coastal forts and distinctive food traditions.',heritagebn:'প্রাচীন নগর, বৌদ্ধ মন্দির, চা-বাগানের পাহাড়, উপকূলীয় দুর্গ ও স্বতন্ত্র খাদ্যঐতিহ্য।',history:'Anuradhapura and Polonnaruwa were influential historic capitals; the island later experienced Portuguese, Dutch and British rule.',historybn:'অনুরাধাপুর ও পোলোনারুয়া ছিল গুরুত্বপূর্ণ ঐতিহাসিক রাজধানী; পরে দ্বীপটি পর্তুগিজ, ডাচ ও ব্রিটিশ শাসনের অধীনে ছিল।'},
{n:'Maldives',bn:'মালদ্বীপ',r:'South Asia',cap:'Malé',capbn:'মালে',img:'photo-1514282401047-d79a71a590e8',heritage:'Atoll island life, coral architecture, lacquer work, boatbuilding and Indian Ocean cuisine.',heritagebn:'অ্যাটল দ্বীপজীবন, প্রবাল স্থাপত্য, ল্যাকার শিল্প, নৌকা নির্মাণ ও ভারত মহাসাগরীয় খাবার।',history:'The islands developed through Indian Ocean trade and adopted Islam in the 12th century, shaping the nation’s cultural identity.',historybn:'ভারত মহাসাগরীয় বাণিজ্যের মাধ্যমে দ্বীপগুলো বিকশিত হয় এবং ১২শ শতকে ইসলাম গ্রহণ দেশের সাংস্কৃতিক পরিচয় গড়ে তোলে।'},
{n:'Afghanistan',bn:'আফগানিস্তান',r:'South Asia',cap:'Kabul',capbn:'কাবুল',img:'photo-1595658658481-d53d3f999875',heritage:'Historic caravan routes, Persianate poetry, traditional crafts and the Bamiyan cultural landscape.',heritagebn:'ঐতিহাসিক বাণিজ্যপথ, ফারসি সাহিত্য, ঐতিহ্যবাহী কারুশিল্প ও বামিয়ানের সাংস্কৃতিক ভূদৃশ্য।',history:'Its position between Central and South Asia connected ancient trade networks and successive regional empires.',historybn:'মধ্য ও দক্ষিণ এশিয়ার সংযোগস্থলে অবস্থানের কারণে প্রাচীন বাণিজ্যপথ ও বিভিন্ন আঞ্চলিক সাম্রাজ্যের সঙ্গে এর সম্পর্ক গড়ে ওঠে।'},
{n:'Japan',bn:'জাপান',r:'Asia',cap:'Tokyo',capbn:'টোকিও',img:'photo-1493976040374-85c8e12f0c0e',heritage:'Shrines, tea ceremony, gardens, traditional crafts and seasonal cherry blossoms.',heritagebn:'শিন্তো মন্দির, চা-অনুষ্ঠান, বাগান, ঐতিহ্যবাহী কারুশিল্প ও ঋতুভিত্তিক চেরি ফুল।',history:'Imperial court culture, samurai rule, the Edo period and rapid modernisation shaped contemporary Japan.',historybn:'রাজদরবারের সংস্কৃতি, সামুরাই শাসন, এদো যুগ ও দ্রুত আধুনিকায়ন আধুনিক জাপানকে গড়েছে।'},
{n:'China',bn:'চীন',r:'Asia',cap:'Beijing',capbn:'বেইজিং',img:'photo-1508804185872-d7badad00f7d',heritage:'The Great Wall, imperial palaces, calligraphy, regional cuisines and traditional festivals.',heritagebn:'মহাপ্রাচীর, রাজপ্রাসাদ, ক্যালিগ্রাফি, আঞ্চলিক খাবার ও ঐতিহ্যবাহী উৎসব।',history:'One of the world’s oldest continuous civilisational traditions, shaped by dynasties, trade routes and philosophical schools.',historybn:'বিশ্বের প্রাচীন ধারাবাহিক সভ্যতাগুলোর একটি; রাজবংশ, বাণিজ্যপথ ও দার্শনিক ধারায় এর ইতিহাস গড়েছে।'},
{n:'Thailand',bn:'থাইল্যান্ড',r:'Asia',cap:'Bangkok',capbn:'ব্যাংকক',img:'photo-1528181304800-259b08848526',heritage:'Buddhist temples, floating markets, classical dance and celebrated street-food culture.',heritagebn:'বৌদ্ধ মন্দির, ভাসমান বাজার, শাস্ত্রীয় নৃত্য ও বিখ্যাত স্ট্রিট-ফুড সংস্কৃতি।',history:'The Sukhothai and Ayutthaya kingdoms shaped Thai culture; Siam remained independent during the colonial era in Southeast Asia.',historybn:'সুখোথাই ও আয়ুথায়া রাজ্য থাই সংস্কৃতি গড়েছে; দক্ষিণ-পূর্ব এশিয়ায় ঔপনিবেশিক যুগে সিয়াম স্বাধীন ছিল।'},
{n:'Malaysia',bn:'মালয়েশিয়া',r:'Asia',cap:'Kuala Lumpur',capbn:'কুয়ালালামপুর',img:'photo-1596422846543-75c6fc197f07',heritage:'Malay, Chinese, Indian and Indigenous traditions, historic Melaka and diverse food cultures.',heritagebn:'মালয়, চীনা, ভারতীয় ও আদিবাসী ঐতিহ্য, ঐতিহাসিক মালাক্কা ও বৈচিত্র্যময় খাবার।',history:'The Malay sultanates and Melaka’s trading port linked the region to major Indian Ocean and East Asian networks.',historybn:'মালয় সালতানাত ও মালাক্কার বন্দর অঞ্চলটিকে ভারত মহাসাগর ও পূর্ব এশিয়ার বাণিজ্য নেটওয়ার্কের সঙ্গে যুক্ত করেছিল।'},
{n:'Singapore',bn:'সিঙ্গাপুর',r:'Asia',cap:'Singapore',capbn:'সিঙ্গাপুর',img:'photo-1525625293386-3f8f99389edd',heritage:'Historic shophouses, Peranakan culture, hawker centres and a multilingual urban identity.',heritagebn:'ঐতিহাসিক শপহাউস, পেরানাকান সংস্কৃতি, হকার সেন্টার ও বহুভাষিক নগর পরিচয়।',history:'A major trading port in the British colonial era, Singapore became an independent republic in 1965.',historybn:'ব্রিটিশ ঔপনিবেশিক যুগে গুরুত্বপূর্ণ বাণিজ্যবন্দর সিঙ্গাপুর ১৯৬৫ সালে স্বাধীন প্রজাতন্ত্র হয়।'},
{n:'Indonesia',bn:'ইন্দোনেশিয়া',r:'Asia',cap:'Jakarta',capbn:'জাকার্তা',img:'photo-1537996194471-e657df975ab4',heritage:'Borobudur and Prambanan, batik, gamelan music and hundreds of local cultural traditions.',heritagebn:'বোরোবুদুর ও প্রামবানান, বাটিক, গামেলান সংগীত এবং শত শত স্থানীয় ঐতিহ্য।',history:'Maritime kingdoms and spice routes connected the archipelago with South and East Asia and the wider world.',historybn:'সমুদ্রভিত্তিক রাজ্য ও মসলা বাণিজ্য দ্বীপপুঞ্জকে দক্ষিণ ও পূর্ব এশিয়া এবং বিশ্বের সঙ্গে যুক্ত করেছিল।'},
{n:'United Arab Emirates',bn:'সংযুক্ত আরব আমিরাত',r:'Asia',cap:'Abu Dhabi',capbn:'আবুধাবি',img:'photo-1512453979798-5ea266f8880c',heritage:'Desert hospitality, pearl-diving heritage, traditional souks and modern architectural landmarks.',heritagebn:'মরুভূমির আতিথেয়তা, মুক্তা আহরণের ঐতিহ্য, ঐতিহ্যবাহী বাজার ও আধুনিক স্থাপত্য।',history:'Coastal trading and pearling communities preceded the federation formed in 1971.',historybn:'১৯৭১ সালে ফেডারেশন গঠনের আগে উপকূলীয় বাণিজ্য ও মুক্তা আহরণভিত্তিক জনপদ ছিল।'},
{n:'Saudi Arabia',bn:'সৌদি আরব',r:'Asia',cap:'Riyadh',capbn:'রিয়াদ',img:'photo-1568322445389-f64ac2515020',heritage:'Makkah and Madinah, Nabataean sites, desert traditions and historic Red Sea trading towns.',heritagebn:'মক্কা ও মদিনা, নাবাতীয় প্রত্নস্থান, মরুভূমির ঐতিহ্য ও লোহিত সাগরের ঐতিহাসিক বাণিজ্যনগর।',history:'The Arabian Peninsula was central to ancient caravan trade and became the birthplace of Islam in the 7th century.',historybn:'আরব উপদ্বীপ প্রাচীন কাফেলা বাণিজ্যের কেন্দ্র ছিল এবং ৭ম শতকে ইসলামের জন্মভূমি হয়।'},
{n:'Turkey',bn:'তুরস্ক',r:'Europe',cap:'Ankara',capbn:'আঙ্কারা',img:'photo-1524231757912-21f4fe3a7200',heritage:'Istanbul’s historic skyline, Ottoman architecture, Anatolian crafts and regional food traditions.',heritagebn:'ইস্তাম্বুলের ঐতিহাসিক দৃশ্য, উসমানীয় স্থাপত্য, আনাতোলীয় কারুশিল্প ও আঞ্চলিক খাবার।',history:'Anatolia hosted Hittite, Greek, Roman, Byzantine and Ottoman societies; the modern republic was founded in 1923.',historybn:'আনাতোলিয়ায় হিট্টাইট, গ্রিক, রোমান, বাইজেন্টাইন ও উসমানীয় সভ্যতা বিকশিত হয়েছে; আধুনিক প্রজাতন্ত্র প্রতিষ্ঠিত হয় ১৯২৩ সালে।'},
{n:'France',bn:'ফ্রান্স',r:'Europe',cap:'Paris',capbn:'প্যারিস',img:'photo-1502602898657-3e91760cbb34',heritage:'Gothic cathedrals, art museums, regional food traditions, historic villages and celebrated design.',heritagebn:'গথিক ক্যাথেড্রাল, শিল্প জাদুঘর, আঞ্চলিক খাবার, ঐতিহাসিক গ্রাম ও নকশাশিল্প।',history:'Roman Gaul, medieval kingdoms, the French Revolution and republican traditions shaped modern France.',historybn:'রোমান গল, মধ্যযুগীয় রাজ্য, ফরাসি বিপ্লব ও প্রজাতান্ত্রিক ঐতিহ্য আধুনিক ফ্রান্সকে গড়েছে।'},
{n:'Italy',bn:'ইতালি',r:'Europe',cap:'Rome',capbn:'রোম',img:'photo-1516483638261-f4dbaf036963',heritage:'Roman monuments, Renaissance art, historic piazzas and distinctive regional cuisines.',heritagebn:'রোমান স্থাপনা, রেনেসাঁ শিল্প, ঐতিহাসিক পিয়াজা ও স্বতন্ত্র আঞ্চলিক খাবার।',history:'The Roman Empire and the Renaissance left an enduring legacy in law, architecture, art and scholarship.',historybn:'রোমান সাম্রাজ্য ও রেনেসাঁ আইন, স্থাপত্য, শিল্প ও জ্ঞানচর্চায় দীর্ঘস্থায়ী প্রভাব রেখেছে।'},
{n:'United Kingdom',bn:'যুক্তরাজ্য',r:'Europe',cap:'London',capbn:'লন্ডন',img:'photo-1513635269975-59663e0ac1ad',heritage:'Castles, historic universities, literary landmarks, music scenes and varied regional traditions.',heritagebn:'দুর্গ, ঐতিহাসিক বিশ্ববিদ্যালয়, সাহিত্যিক স্থান, সংগীতধারা ও আঞ্চলিক ঐতিহ্য।',history:'The union of historic kingdoms, industrialisation and a global maritime empire shaped the UK’s modern history.',historybn:'ঐতিহাসিক রাজ্যগুলোর একীকরণ, শিল্পবিপ্লব ও বৈশ্বিক সামুদ্রিক সাম্রাজ্য যুক্তরাজ্যের আধুনিক ইতিহাস গড়েছে।'},
{n:'Spain',bn:'স্পেন',r:'Europe',cap:'Madrid',capbn:'মাদ্রিদ',img:'photo-1509840841025-9088ba78a826',heritage:'Moorish palaces, Gothic cathedrals, flamenco, regional festivals and distinctive architecture.',heritagebn:'মুরিশ প্রাসাদ, গথিক ক্যাথেড্রাল, ফ্লামেঙ্কো, আঞ্চলিক উৎসব ও স্বতন্ত্র স্থাপত্য।',history:'Roman, Islamic Andalusian and Christian kingdoms shaped Spain, followed by a major early-modern overseas empire.',historybn:'রোমান, ইসলামী আন্দালুসীয় ও খ্রিস্টীয় রাজ্য স্পেনকে গড়েছে; পরে গড়ে ওঠে প্রভাবশালী সামুদ্রিক সাম্রাজ্য।'},
{n:'Switzerland',bn:'সুইজারল্যান্ড',r:'Europe',cap:'Bern',capbn:'বার্ন',img:'photo-1531366936337-7c912a4589a7',heritage:'Alpine villages, watchmaking, folk music, historic old towns and multilingual traditions.',heritagebn:'আল্পাইন গ্রাম, ঘড়ি নির্মাণ, লোকসংগীত, পুরোনো শহর ও বহুভাষিক ঐতিহ্য।',history:'The Swiss Confederacy developed through regional alliances and a long tradition of cantonal autonomy.',historybn:'আঞ্চলিক জোট ও ক্যান্টনভিত্তিক স্বায়ত্তশাসনের দীর্ঘ ঐতিহ্য থেকে সুইস কনফেডারেশন গড়ে ওঠে।'},
{n:'Greece',bn:'গ্রিস',r:'Europe',cap:'Athens',capbn:'এথেন্স',img:'photo-1533105079780-92b9be482077',heritage:'Classical temples, island villages, Byzantine churches and a rich maritime food culture.',heritagebn:'প্রাচীন মন্দির, দ্বীপের গ্রাম, বাইজেন্টাইন গির্জা ও সমৃদ্ধ সামুদ্রিক খাদ্যসংস্কৃতি।',history:'Ancient Greek city-states influenced philosophy, drama and political thought; later Byzantine and Ottoman eras also shaped the region.',historybn:'প্রাচীন গ্রিক নগররাষ্ট্র দর্শন, নাটক ও রাজনৈতিক চিন্তায় প্রভাব রেখেছে; পরে বাইজেন্টাইন ও উসমানীয় যুগও অঞ্চলটিকে গড়েছে।'},
{n:'Germany',bn:'জার্মানি',r:'Europe',cap:'Berlin',capbn:'বার্লিন',img:'photo-1467269204594-9661b134dd2b',heritage:'Medieval towns, castles, classical music, Christmas markets and Bauhaus design.',heritagebn:'মধ্যযুগীয় শহর, দুর্গ, ধ্রুপদি সংগীত, বড়দিনের বাজার ও বাউহাউস নকশা।',history:'German-speaking lands were shaped by the Holy Roman Empire, unification in 1871, division after World War II and reunification in 1990.',historybn:'পবিত্র রোমান সাম্রাজ্য, ১৮৭১ সালের একীকরণ, দ্বিতীয় বিশ্বযুদ্ধের পর বিভাজন এবং ১৯৯০ সালের পুনরেকত্রীকরণ ইতিহাসের গুরুত্বপূর্ণ অধ্যায়।'},
{n:'Egypt',bn:'মিশর',r:'Africa',cap:'Cairo',capbn:'কায়রো',img:'assets/country-egypt.jpg',heritage:'Pyramids, temples along the Nile, Islamic Cairo, Coptic heritage and traditional crafts.',heritagebn:'পিরামিড, নীল নদের তীরের মন্দির, ইসলামিক কায়রো, কপটিক ঐতিহ্য ও কারুশিল্প।',history:'Ancient Egyptian civilisation developed along the Nile; later Greek, Roman, Arab and Ottoman periods added cultural layers.',historybn:'নীল নদের তীরে প্রাচীন মিশরীয় সভ্যতা গড়ে ওঠে; পরে গ্রিক, রোমান, আরব ও উসমানীয় যুগ নতুন সাংস্কৃতিক স্তর যোগ করে।'},
{n:'Morocco',bn:'মরক্কো',r:'Africa',cap:'Rabat',capbn:'রাবাত',img:'photo-1489749798305-4fea3ae63d43',heritage:'Medinas, geometric tilework, Amazigh crafts, souks and desert caravan traditions.',heritagebn:'মদিনা, জ্যামিতিক টাইলশিল্প, আমাজিঘ কারুশিল্প, সুক বাজার ও মরুভূমির কাফেলা ঐতিহ্য।',history:'Amazigh communities and successive dynasties connected Morocco with trans-Saharan and Mediterranean trade.',historybn:'আমাজিঘ জনগোষ্ঠী ও বিভিন্ন রাজবংশ মরক্কোকে সাহারা-পার ও ভূমধ্যসাগরীয় বাণিজ্যের সঙ্গে যুক্ত করেছে।'},
{n:'South Africa',bn:'দক্ষিণ আফ্রিকা',r:'Africa',cap:'Pretoria (administrative)',capbn:'প্রিটোরিয়া (প্রশাসনিক)',img:'photo-1580060839134-75a5edca2e99',heritage:'Indigenous cultures, Cape Malay traditions, rock art, music and diverse regional cuisines.',heritagebn:'আদিবাসী সংস্কৃতি, কেপ মালয় ঐতিহ্য, শিলাচিত্র, সংগীত ও বৈচিত্র্যময় খাবার।',history:'The region’s history includes ancient communities, colonial rule, apartheid and the democratic transition of 1994.',historybn:'এ অঞ্চলের ইতিহাসে প্রাচীন জনসমাজ, ঔপনিবেশিক শাসন, বর্ণবৈষম্য এবং ১৯৯৪ সালের গণতান্ত্রিক পরিবর্তন রয়েছে।'},
{n:'Kenya',bn:'কেনিয়া',r:'Africa',cap:'Nairobi',capbn:'নাইরোবি',img:'photo-1516026672322-bc52d61a55d5',heritage:'Swahili coastal towns, Maasai traditions, beadwork, music and wildlife landscapes.',heritagebn:'সোয়াহিলি উপকূলীয় শহর, মাসাই ঐতিহ্য, পুঁতির কাজ, সংগীত ও বন্যপ্রাণীর ভূদৃশ্য।',history:'Indian Ocean trade shaped the coast, while the modern state emerged after British colonial rule and independence in 1963.',historybn:'ভারত মহাসাগরীয় বাণিজ্য উপকূলকে গড়েছে; ব্রিটিশ শাসনের অবসান ও ১৯৬৩ সালের স্বাধীনতার পর আধুনিক রাষ্ট্র গড়ে ওঠে।'},
{n:'Tanzania',bn:'তানজানিয়া',r:'Africa',cap:'Dodoma',capbn:'দোদোমা',img:'photo-1516426122078-c23e76319801',heritage:'Swahili coastal culture, historic Zanzibar, Maasai traditions and Kilimanjaro landscapes.',heritagebn:'সোয়াহিলি উপকূলীয় সংস্কৃতি, ঐতিহাসিক জানজিবার, মাসাই ঐতিহ্য ও কিলিমাঞ্জারোর দৃশ্য।',history:'Zanzibar was a major Indian Ocean trading centre; Tanganyika and Zanzibar united to form Tanzania in 1964.',historybn:'জানজিবার ভারত মহাসাগরীয় বাণিজ্যের গুরুত্বপূর্ণ কেন্দ্র ছিল; ১৯৬৪ সালে তাঙ্গানিকা ও জানজিবার একত্রে তানজানিয়া গঠন করে।'},
{n:'Ghana',bn:'ঘানা',r:'Africa',cap:'Accra',capbn:'আক্রা',img:'photo-1516026672322-bc52d61a55d5',heritage:'Kente weaving, Adinkra symbols, vibrant festivals and historic coastal forts.',heritagebn:'কেনটে বয়ন, আদিঙ্ক্রা প্রতীক, প্রাণবন্ত উৎসব ও ঐতিহাসিক উপকূলীয় দুর্গ।',history:'The region included powerful Akan states and became an early centre of independence movements in sub-Saharan Africa; Ghana became independent in 1957.',historybn:'এ অঞ্চলে শক্তিশালী আকান রাষ্ট্র ছিল; সাব-সাহারান আফ্রিকার স্বাধীনতা আন্দোলনের অগ্রণী কেন্দ্র হিসেবে ঘানা ১৯৫৭ সালে স্বাধীন হয়।'},
{n:'United States',bn:'যুক্তরাষ্ট্র',r:'North America',cap:'Washington, D.C.',capbn:'ওয়াশিংটন, ডি.সি.',img:'photo-1501594907352-04cda38ebc29',heritage:'Indigenous cultural traditions, jazz, national parks, historic districts and many immigrant food cultures.',heritagebn:'আদিবাসী ঐতিহ্য, জ্যাজ সংগীত, জাতীয় উদ্যান, ঐতিহাসিক এলাকা ও অভিবাসী খাদ্যসংস্কৃতি।',history:'Indigenous nations predate European colonisation; the United States declared independence in 1776 and later expanded across the continent.',historybn:'ইউরোপীয় উপনিবেশের বহু আগে আদিবাসী জাতিসমূহ ছিল; যুক্তরাষ্ট্র ১৭৭৬ সালে স্বাধীনতা ঘোষণা করে এবং পরে মহাদেশজুড়ে বিস্তৃত হয়।'},
{n:'Canada',bn:'কানাডা',r:'North America',cap:'Ottawa',capbn:'অটোয়া',img:'assets/country-canada.jpg',heritage:'First Nations, Inuit and Métis cultures, French-speaking Québec, Indigenous art and vast natural landscapes.',heritagebn:'ফার্স্ট নেশনস, ইনুইট ও মেটিস সংস্কৃতি, ফরাসিভাষী কুইবেক, আদিবাসী শিল্প ও বিস্তৃত প্রাকৃতিক দৃশ্য।',history:'Indigenous peoples have lived here for millennia; French and British colonial histories preceded Confederation in 1867.',historybn:'সহস্রাব্দ ধরে আদিবাসীরা এখানে বসবাস করছেন; ফরাসি ও ব্রিটিশ ঔপনিবেশিক ইতিহাসের পর ১৮৬৭ সালে কনফেডারেশন গঠিত হয়।'},
{n:'Mexico',bn:'মেক্সিকো',r:'North America',cap:'Mexico City',capbn:'মেক্সিকো সিটি',img:'photo-1512813195386-6cf811ad3542',heritage:'Maya and Aztec sites, Día de Muertos, colourful crafts, mariachi and regional cuisine.',heritagebn:'মায়া ও অ্যাজটেক নিদর্শন, দিয়া দে মুয়ের্তোস, রঙিন কারুশিল্প, মারিয়াচি ও আঞ্চলিক খাবার।',history:'Mesoamerican civilisations preceded Spanish rule; Mexico became independent in 1821 and retains a layered cultural identity.',historybn:'স্প্যানিশ শাসনের আগে মেসোআমেরিকান সভ্যতাগুলো বিকশিত হয়; মেক্সিকো ১৮২১ সালে স্বাধীন হয়।'},
{n:'Costa Rica',bn:'কোস্টা রিকা',r:'North America',cap:'San José',capbn:'সান হোসে',img:'photo-1510414842594-a61c69b5ae57',heritage:'Coffee traditions, biodiversity, rural festivals and conservation-focused national parks.',heritagebn:'কফির ঐতিহ্য, জীববৈচিত্র্য, গ্রামীণ উৎসব ও সংরক্ষণকেন্দ্রিক জাতীয় উদ্যান।',history:'Indigenous societies preceded Spanish colonisation; Costa Rica became independent from Spain in 1821.',historybn:'স্প্যানিশ উপনিবেশের আগে আদিবাসী সমাজ ছিল; কোস্টা রিকা ১৮২১ সালে স্পেন থেকে স্বাধীন হয়।'},
{n:'Brazil',bn:'ব্রাজিল',r:'South America',cap:'Brasília',capbn:'ব্রাসিলিয়া',img:'photo-1483729558449-99ef09a8c325',heritage:'Amazonian and Indigenous traditions, Afro-Brazilian culture, samba, carnival and regional cuisine.',heritagebn:'আমাজনীয় ও আদিবাসী ঐতিহ্য, আফ্রো-ব্রাজিলীয় সংস্কৃতি, সাম্বা, কার্নিভাল ও আঞ্চলিক খাবার।',history:'Portuguese colonisation, Indigenous peoples and the African diaspora deeply shaped Brazil; independence came in 1822.',historybn:'পর্তুগিজ উপনিবেশ, আদিবাসী জনগোষ্ঠী ও আফ্রিকান প্রবাসী জনগোষ্ঠী ব্রাজিলকে গভীরভাবে গড়েছে; ১৮২২ সালে স্বাধীনতা আসে।'},
{n:'Peru',bn:'পেরু',r:'South America',cap:'Lima',capbn:'লিমা',img:'photo-1526392060635-9d6019884377',heritage:'Machu Picchu, Andean textiles, Quechua traditions and distinctive regional foods.',heritagebn:'মাচু পিচু, আন্দীয় বস্ত্রশিল্প, কেচুয়া ঐতিহ্য ও স্বতন্ত্র আঞ্চলিক খাবার।',history:'The Inca Empire flourished in the Andes before Spanish conquest; Indigenous heritage remains central to national identity.',historybn:'স্প্যানিশ বিজয়ের আগে আন্দেসে ইনকা সাম্রাজ্য বিকশিত হয়; জাতীয় পরিচয়ে আদিবাসী ঐতিহ্য এখনও গুরুত্বপূর্ণ।'},
{n:'Argentina',bn:'আর্জেন্টিনা',r:'South America',cap:'Buenos Aires',capbn:'বুয়েনোস আইরেস',img:'photo-1516026672322-bc52d61a55d5',heritage:'Tango, gaucho traditions, literary cafés, Andean communities and regional food culture.',heritagebn:'ট্যাঙ্গো, গাউচো ঐতিহ্য, সাহিত্যিক ক্যাফে, আন্দীয় জনগোষ্ঠী ও আঞ্চলিক খাদ্যসংস্কৃতি।',history:'Spanish colonial rule ended with independence in 1816; later migration shaped the country’s diverse urban culture.',historybn:'১৮১৬ সালে স্প্যানিশ শাসনের অবসান ও স্বাধীনতার পর অভিবাসন দেশটির বৈচিত্র্যময় নগর সংস্কৃতি গড়ে তোলে।'},
{n:'Chile',bn:'চিলি',r:'South America',cap:'Santiago',capbn:'সান্তিয়াগো',img:'photo-1464822759023-fed622ff2c3b',heritage:'Mapuche traditions, Pacific coastal culture, Andean landscapes and distinctive wine regions.',heritagebn:'মাপুচে ঐতিহ্য, প্রশান্ত মহাসাগরীয় উপকূলীয় সংস্কৃতি, আন্দীয় ভূদৃশ্য ও বিখ্যাত ওয়াইন অঞ্চল।',history:'Indigenous societies and Spanish colonial rule shaped Chile before independence in 1818.',historybn:'আদিবাসী সমাজ ও স্প্যানিশ ঔপনিবেশিক শাসনের পর ১৮১৮ সালে চিলি স্বাধীন হয়।'},
{n:'Australia',bn:'অস্ট্রেলিয়া',r:'Oceania',cap:'Canberra',capbn:'ক্যানবেরা',img:'photo-1506973035872-a4ec16b8e8d9',heritage:'Aboriginal and Torres Strait Islander cultures, Dreaming stories, coastal life and distinctive wildlife.',heritagebn:'অ্যাবরিজিনাল ও টরেস স্ট্রেইট আইল্যান্ডার সংস্কৃতি, ড্রিমিং কাহিনি, উপকূলীয় জীবন ও অনন্য বন্যপ্রাণী।',history:'First Nations peoples have maintained cultures for tens of thousands of years; British colonisation began in 1788 and federation followed in 1901.',historybn:'ফার্স্ট নেশনস জনগোষ্ঠী হাজার হাজার বছর ধরে সংস্কৃতি ধরে রেখেছেন; ১৭৮৮ সালে ব্রিটিশ উপনিবেশ শুরু এবং ১৯০১ সালে ফেডারেশন হয়।'},
{n:'New Zealand',bn:'নিউজিল্যান্ড',r:'Oceania',cap:'Wellington',capbn:'ওয়েলিংটন',img:'photo-1469521669194-babb45599def',heritage:'Māori language and carving, kapa haka performance, Pacific influences and spectacular landscapes.',heritagebn:'মাওরি ভাষা ও খোদাইশিল্প, কাপা হাকা পরিবেশনা, প্রশান্ত মহাসাগরীয় প্রভাব ও অসাধারণ ভূদৃশ্য।',history:'Māori settlement preceded European arrival; Te Tiriti o Waitangi / Treaty of Waitangi was signed in 1840.',historybn:'ইউরোপীয় আগমনের আগে মাওরি বসতি ছিল; ১৮৪০ সালে তে তিরিতি ওয়াইতাঙ্গি চুক্তি স্বাক্ষরিত হয়।'},
{n:'Fiji',bn:'ফিজি',r:'Oceania',cap:'Suva',capbn:'সুভা',img:'photo-1500375592092-40eb2168fd21',heritage:'iTaukei traditions, communal ceremonies, meke dance and Indo-Fijian cultural influences.',heritagebn:'ইতাউকেই ঐতিহ্য, সামষ্টিক অনুষ্ঠান, মেকে নৃত্য ও ইন্দো-ফিজীয় সাংস্কৃতিক প্রভাব।',history:'The islands have long Pacific voyaging traditions; Fiji became independent from Britain in 1970.',historybn:'দ্বীপগুলোতে দীর্ঘ প্রশান্ত মহাসাগরীয় নৌযাত্রার ঐতিহ্য রয়েছে; ফিজি ১৯৭০ সালে ব্রিটেন থেকে স্বাধীন হয়।'},
{n:'Samoa',bn:'সামোয়া',r:'Oceania',cap:'Apia',capbn:'আপিয়া',img:'photo-1507525428034-b723cf961d3e',heritage:'Fa’a Samoa, communal village life, tatau tattooing traditions, dance and Pacific navigation.',heritagebn:'ফা‘আ সামোয়া, সামষ্টিক গ্রামজীবন, তাতাউ উল্কি ঐতিহ্য, নৃত্য ও প্রশান্ত মহাসাগরীয় নৌচালনা।',history:'Samoan society has a deep Polynesian heritage; the country became independent in 1962, the first in the Pacific island region.',historybn:'সামোয়ান সমাজের গভীর পলিনেশীয় ঐতিহ্য রয়েছে; ১৯৬২ সালে দেশটি স্বাধীন হয়, যা প্রশান্ত মহাসাগরীয় দ্বীপ অঞ্চলে প্রথম।'}
];
let activeRegion='All';const countryGrid=document.getElementById('countryGrid');const countrySearch=document.getElementById('countrySearch');
function imageUrl(id){return id.startsWith('assets/') ? id : `https://images.unsplash.com/${id}?auto=format&fit=crop&w=700&q=75`}
function renderCountries(){if(!countryGrid)return;const q=(countrySearch?.value||'').trim().toLowerCase();const list=countries.filter(c=>(activeRegion==='All'||c.r===activeRegion)&&(c.n.toLowerCase().includes(q)||c.bn.includes(q)||c.cap.toLowerCase().includes(q)));if(!list.length){countryGrid.innerHTML=`<div class="no-results">${currentLang==='bn'?'কোনো দেশ পাওয়া যায়নি। অন্য নাম দিয়ে খুঁজুন।':'No countries found. Try another search.'}</div>`;return}countryGrid.innerHTML=list.map(c=>`<article class="country-card"><div class="country-image"><img src="${imageUrl(c.img)}" alt="${c.n} landscape or heritage" loading="lazy"><span class="region-tag">${currentLang==='bn'?(c.r==='South Asia'?'দক্ষিণ এশিয়া':c.r==='Asia'?'এশিয়া':c.r==='Europe'?'ইউরোপ':c.r==='Africa'?'আফ্রিকা':c.r==='North America'?'উত্তর আমেরিকা':c.r==='South America'?'দক্ষিণ আমেরিকা':'ওশেনিয়া'):c.r}</span></div><div class="country-content"><div class="country-title-row"><h3>${currentLang==='bn'?c.bn:c.n}</h3></div><div class="country-capital">${currentLang==='bn'?'রাজধানী':'Capital'}: ${currentLang==='bn'?c.capbn:c.cap}</div><div class="country-heritage"><b>${currentLang==='bn'?'ঐতিহ্য':'Heritage'}:</b> ${currentLang==='bn'?c.heritagebn:c.heritage}</div><div class="country-history"><b>${currentLang==='bn'?'ইতিহাস':'History'}:</b> ${currentLang==='bn'?c.historybn:c.history}</div><a class="country-enquire" href="#enquiry" data-en="Enquire about travel ↗" data-bn="ভ্রমণ সম্পর্কে জিজ্ঞাসা ↗">${currentLang==='bn'?'ভ্রমণ সম্পর্কে জিজ্ঞাসা ↗':'Enquire about travel ↗'}</a></div></article>`).join('')}
document.querySelectorAll('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{activeRegion=btn.dataset.region;document.querySelectorAll('.filter-btn').forEach(b=>b.classList.toggle('active',b===btn));renderCountries()}));if(countrySearch)countrySearch.addEventListener('input',renderCountries);
const navLinks=[...document.querySelectorAll('.nav-link')];const sections=navLinks.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+entry.target.id))}})},{rootMargin:'-30% 0px -60% 0px'});sections.forEach(s=>observer.observe(s))}
const enquiryForm=document.getElementById('enquiryForm');if(enquiryForm){enquiryForm.addEventListener('submit',e=>{e.preventDefault();if(!enquiryForm.reportValidity())return;const d=new FormData(enquiryForm);const body=[`Name: ${d.get('name')}`,`Phone/WhatsApp: ${d.get('phone')}`,`Service: ${d.get('service')}`,`Message: ${d.get('message')||'No additional message'}`].join('\n');window.location.href=`mailto:continentalflyway@gmail.com?subject=${encodeURIComponent('Website enquiry — '+d.get('service'))}&body=${encodeURIComponent(body)}`;document.getElementById('formMessage').textContent=currentLang==='bn'?'আপনার ইমেইল অ্যাপ খুলবে। বার্তাটি পাঠাতে সেখানে Send চাপুন।':'Your email app should open with the enquiry. Press Send there to submit it.'})}
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();renderCountries();
